drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 team varchar(255),
 title varchar(255),
 text text(1000),
 register_time timestamp default current_timestamp,
 primary key (id)
);